# GENERATED BY SERVEY-STUB
# Manual updates to this file may be lost. 
# Updated At: 2024-02-25T17:32:04.212933
import requests
from marshy.types import ExternalItemType, ExternalType


def invoke(
    url: str, method: str, event: ExternalItemType, timeout: int = 15
) -> ExternalType:
    if method.upper() in ("POST", "PUT", "PATCH"):
        response = requests.request(method, url, json=event, timeout=timeout)
    else:
        response = requests.request(method, url, params=event, timeout=timeout)
    return response.json()
