# GENERATED BY SERVEY-STUB
# Manual updates to this file may be lost. 
# Updated At: 2024-02-25T17:32:04.213154
import setuptools

setuptools.setup(
    name="servey_main",
    version="0.1.0",
    packages=setuptools.find_packages(exclude=("tests*")),
    install_requires=['marshy', 'requests'],
)
